### ISSUE TITLE
32.768 oscillator necessary?

### ISSUE THREAD

**Issue by flybrianfly** [kriswiner/Ladybug#6]
Hey Kris,

Making a custom board after prototyping with the Ladybug. Wondering if you know offhand if the 32.768 oscillator is needed if I'm not using the RTC? Would the core software need to be updated?

Thanks much!

**Comment by kriswiner** [comment]
Definitely required if you want to use the Tlera Corp Arduino core...

**Comment by flybrianfly** [comment]
Hi @kriswiner, can you provide part numbers or specs for the oscillator and caps? I designed a custom board after prototyping with a Ladybug, but the USB isn't coming up and I'm suspecting that it's an issue with the oscillator I used. Thanks!

**Comment by kriswiner** [comment]
Any 20 ppm 32.768 kHz crystal with 4 pF capacitance. I use 5.6 pF balancing
caps.

Send me your schematic and I will take a look.

**Comment by flybrianfly** [comment]
Thanks @kriswiner! Just sent you an email. I'm suspecting maybe an issue with the oscillator and caps, I used a 6 pF oscillator and 4.3 pF balancing caps.

**Comment by kriswiner** [comment]
Nope, must connect VBUS to PA15 for USB serial to work in this design.

**Comment by flybrianfly** [comment]
Thanks! I managed to bodge that connection and it's working as expected now.
